describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://test1.creditfair.in/admin/login')
    cy.get('input[name="username"]').type('tejas')
    cy.get('input[name="password"]').type('1234')
    cy.get("#m_login_signin_submit").click()
    cy.get('#m_ver_menu > ul > li:nth-child(4) > a > span > span > span').click()
    cy.get('#m_ver_menu > ul > li:nth-child(4) > ul > li:nth-child(2) > a:nth-child(2)').click()
    cy.get('#tr_2411 > td:nth-child(11) > span:nth-child(2) > i')
    cy.get('#tr_2411 > td:nth-child(11) > span:nth-child(2)').click()
    cy.get('.dropdown.show > .dropdown-menu > [data-status="waiting for documents"] > a').click()
    cy.get('.pending_doc_list > .row > .btn-group > .btn > .filter-option').click()
    cy.get('#update_status_comment > div > div > div.modal-body > div.pending_doc_list > div > div > button').click()
    cy.get('#update_status_comment > div > div > div.modal-body > div.pending_doc_list > div > div > div > ul')
    cy.get('#update_status_comment > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
    cy.get('#update_status_comment > div > div > div.modal-body > div.pending_doc_list > div > div > button > span.filter-option.pull-left')
    cy.get('.pending_doc_list > .row > .btn-group > .open > .dropdown-menu > [data-original-index="2"] > a > .text')
    cy.get('#update_status_comment > div > div > div.modal-body > div.pending_doc_list > div > div > div > ul > li:nth-child(3)')
    //cy.get('#update_status_comment > div > div > div.modal-body > div.pending_doc_list > div > div > div > ul > li.selected > a > span.text')
    //cy.xpath('//*[@id="update_status_comment"]/div/div/div[1]/div[1]/div/div/div/ul/li[3]')
    //cy.get('[@id="update_status_comment"]')
    cy.xpath('//*[@id="update_status_comment"]/div/div/div[1]/div[1]/div/div/button/span[1]').should("be.visible");
    cy.xpath('//*[@id="update_status_comment"]/div/div/div[1]/div[1]/div/div/button/span[1]').click()
    cy.get('.pending_doc_list > .row > .btn-group > .open > .dropdown-menu > [data-original-index="0"] > a').click()
    cy.get('.pending_doc_list').click()
    cy.get('#update_status_comment > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
   
  })
})